### ISSUE TITLE
Crash on Borg Assimilation combat

### ISSUE THREAD

**Issue by ExultantMonkey** [BotF2/BotF2#1]
AssimilatedCombatEngine
// Check for IsAssmilated and in combat with Borg for (int i = 0; i < _combatShips.Count; i++) { CombatAssets ownerBorg = GetAssets(_combatShips[i].First.Owner); if (ownerBorg.Owner.Name.ToString() != "Borg") continue; goto Next; {

**Comment by KennethGF** [comment]
Got a crash in CombatEngine.cs at the last line of code see here, line 88 in my version. Might be something to do with surviving assets count?       

 public bool IsCombatOver
        {
            get
            {
                if (_allSidesStandDown)
                    return true;
                //if (_assets.Count(assets => assets.CombatShips.);
                return (_assets.Count(assets => assets.HasSurvivingAssets) <= 1);
            }
        }

**Comment by ExultantMonkey** [comment]
That one has been reported at #6

**Comment by KennethGF** [comment]
Getting an error out of Borg combat from PerformAssimilation() and PerformRetreat() in CombatEngine.cs?

Looking like the OnwerID is still null at some point?

System.Collections.Generic.KeyNotFoundException
  HResult=0x80131577
  Message=The given key was not present in the dictionary.
  Source=SupremacyCore
  StackTrace:
   at Supremacy.Collections.KeyedCollectionBase`2.get_Item(TKey key) in C:\Users\Kenneth Flanagan\Documents\1A_20180415_BOTF2\BotF2\SupremacyCore\Collections\ObservableKeyedCollection.cs:line 107
   at Supremacy.Orbitals.Fleet.OnLocationChanged() in C:\Users\Kenneth Flanagan\Documents\1A_20180415_BOTF2\BotF2\SupremacyCore\Orbitals\Fleet.cs:line 623
   at Supremacy.Universe.UniverseObject.set_Location(MapLocation value) in C:\Users\Kenneth Flanagan\Documents\1A_20180415_BOTF2\BotF2\SupremacyCore\Universe\UniverseObject.cs:line 257
   at Supremacy.Combat.CombatEngine.PerformRetreat() in C:\Users\Kenneth Flanagan\Documents\1A_20180415_BOTF2\BotF2\SupremacyCore\Combat\CombatEngine.cs:line 435
   at Supremacy.Combat.CombatEngine.ResolveCombatRound() in C:\Users\Kenneth Flanagan\Documents\1A_20180415_BOTF2\BotF2\SupremacyCore\Combat\CombatEngine.cs:line 169
   at Supremacy.WCF.SupremacyService.TryResumeCombat(CombatEngine engine) in C:\Users\Kenneth Flanagan\Documents\1A_20180415_BOTF2\BotF2\SupremacyService\SupremacyService.cs:line 1232

**Comment by KennethGF** [comment]
KeyedCollectionBase<GameObjectID, Civiliation> is read only 

So cannot be updated on assimilation? Workaround with remove and replace with a Borg game object?

**Comment by ExultantMonkey** [comment]
I've had a quick look at it and the problem is that the OwnerID is null like you said, the read only has nothing to do with it.

The owner is set in CombatEngine:PerformAssimilation() with the line _ship.Fleet.OwnerID = 7;

Need to figure out how this value propogates, or even if this is the right thing to do. Surely we should be applying it to the individual ship and then transferring that ship to the Borg fleet.

Now that I know where to look I'll start working on it slowly. My time will be freeing up in the next few weeks

**Comment by bote-reginald** [comment]
Oh God, sorry. When we unskilled coders coded this -> Borg was 7.  Meanwhile we throw out "INTRO"-race we implemented for some -resolved now- UI problems. Now Borg are 6, (Fed = 0)

**Comment by ExultantMonkey** [comment]
Ah, that's a nice easy fix then

**Comment by KennethGF** [comment]
Thanks 👍

**Comment by ExultantMonkey** [comment]
Since your doing a lot in the combat code I'll let you make the change, otherwise things might get conflicted when it goes in to master

**Comment by KennethGF** [comment]
Not crashing but working on combat with assimilated ships now

**Comment by KennethGF** [comment]
Appears to be working
