### ISSUE TITLE
DoStartGame \SupremacyService.cs:line 244

### ISSUE THREAD

**Issue by KennethGF** [BotF2/BotF2#115]
Game stops loading on master branch after clicking start. 
(end of log.txt)
  at Supremacy.Universe.GalaxyGenerator.GenerateGalaxy(GameContext game) in C:\Users\Kenneth Flanagan\Documents\00_BOTF2_20180729\BotF2\SupremacyCore\Universe\GalaxyGenerator.cs:line 216
   at Supremacy.Game.GameContext.Initialize() in C:\Users\Kenneth Flanagan\Documents\00_BOTF2_20180729\BotF2\SupremacyCore\Game\GameContext.cs:line 835
   at Supremacy.Game.GameContext..ctor(GameOptions options, Boolean isMultiplayerGame) in C:\Users\Kenneth Flanagan\Documents\00_BOTF2_20180729\BotF2\SupremacyCore\Game\GameContext.cs:line 774
   at Supremacy.Game.GameContext.Create(GameOptions options, Boolean isMultiplayerGame) in C:\Users\Kenneth Flanagan\Documents\00_BOTF2_20180729\BotF2\SupremacyCore\Game\GameContext.cs:line 760
   at Supremacy.WCF.SupremacyService.DoStartGame() in C:\Users\Kenneth Flanagan\Documents\00_BOTF2_20180729\BotF2\SupremacyService\SupremacyService.cs:line 244

(Debug output ended with this)
'SupremacyClient.exe' (CLR v4.0.30319: SupremacyClient.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.EnterpriseServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.EnterpriseServices.Wrapper.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
writing FromTechObj-ShipNames_(autoCreated).csv
writing FromTechObj-Ships_(autoCreated).csv
writing FromTechObj-Shipyards_(autoCreated).csv
Exception thrown: 'System.Xml.XmlException' in System.Xml.dll
writing FromTechObj-ShipNames_(autoCreated).csv
writing FromTechObj-Ships_(autoCreated).csv
writing FromTechObj-Shipyards_(autoCreated).csv
Exception thrown: 'System.Xml.XmlException' in System.Xml.dll
The program '[18116] SupremacyClient.exe' has exited with code -1 (0xffffffff).

**Comment by ExultantMonkey** [comment]
HomeSystems.xml in the resource folder is invalid

**Comment by ExultantMonkey** [comment]
Fixed in Dropbox. Copy the new HomeSystems.xml and it should be absolutely fine

**Comment by KennethGF** [comment]
thanks for fixing my mistake.
