### ISSUE TITLE
Exception in DoIntelligence

### ISSUE THREAD

**Issue by KennethGF** [BotF2/BotF2#123]
09:51:44.765 [34] DEBUG General - EXCEPTION OCCURRED in <>c__DisplayClass55_0.<DoIntelligence>b__0()
09:51:44.767 [36] DEBUG General -   Exception source:  SupremacyCore
09:51:44.768 [36] DEBUG General -   Exception message: Specified argument was out of the range of valid values.
09:51:44.768 [36] DEBUG General -   InnerException:    
09:51:44.769 [22] DEBUG General -   Exception source:  SupremacyCore
09:51:44.769 [22] DEBUG General -   Exception message: Specified argument was out of the range of valid values.
09:51:44.768 [26] DEBUG General -   Exception source:  SupremacyCore
09:51:44.770 [26] DEBUG General -   Exception message: Specified argument was out of the range of valid values.
09:51:44.769 [35] DEBUG General -   Exception source:  SupremacyCore
09:51:44.771 [35] DEBUG General -   Exception message: Specified argument was out of the range of valid values.
09:51:44.771 [35] DEBUG General -   InnerException:    
09:51:44.770 [22] DEBUG General -   InnerException:    
09:51:44.773 [22] DEBUG General -   TargetSite:        Int32 Next(Int32, Int32)
09:51:44.769 [34] DEBUG General -   Exception source:  SupremacyCore
09:51:44.774 [34] DEBUG General -   Exception message: Specified argument was out of the range of valid values.
09:51:44.775 [34] DEBUG General -   InnerException:    
09:51:44.775 [34] DEBUG General -   TargetSite:        Int32 Next(Int32, Int32)
09:51:44.769 [36] DEBUG General -   TargetSite:        Int32 Next(Int32, Int32)
09:51:44.776 [36] DEBUG General -   Exception StackTrace:    at Supremacy.Utility.MersenneTwister.Next(Int32 minValue, Int32 maxValue) in C:\Users\Kenneth Flanagan\Documents\00_BOTF2_20180729\BotF2\SupremacyCore\Utility\Random\MersenneTwister.cs:line 230
   at Supremacy.Game.GameEngine.<>c__DisplayClass55_0.<DoIntelligence>b__0(Civilization civ) in C:\Users\Kenneth Flanagan\Documents\00_BOTF2_20180729\BotF2\SupremacyCore\Game\GameEngine.cs:line 1539

**Comment by KennethGF** [comment]
09:51:44.759 [35] DEBUG General - EXCEPTION OCCURRED in <>c__DisplayClass55_0.<DoIntelligence>b__0()
09:51:44.759 [22] DEBUG General - <>c__DisplayClass55_0.<DoIntelligence>b__0(): DoIntelligience failed for Cardassians
09:51:44.760 [26] DEBUG General - <>c__DisplayClass55_0.<DoIntelligence>b__0(): DoIntelligience failed for Federation
09:51:44.761 [26] DEBUG General - 
09:51:44.759 [36] DEBUG General - <>c__DisplayClass55_0.<DoIntelligence>b__0(): DoIntelligience failed for Terran Empire
09:51:44.762 [36] DEBUG General - 
09:51:44.761 [22] DEBUG General - 
09:51:44.763 [22] DEBUG General - EXCEPTION OCCURRED in <>c__DisplayClass55_0.<DoIntelligence>b__0()
09:51:44.762 [26] DEBUG General - EXCEPTION OCCURRED in <>c__DisplayClass55_0.<DoIntelligence>b__0()
09:51:44.759 [34] DEBUG General - <>c__DisplayClass55_0.<DoIntelligence>b__0(): DoIntelligience failed for Klingons
