### ISSUE TITLE
redeploy ships in a fleet null reference

### ISSUE THREAD

**Issue by KennethGF** [BotF2/BotF2#143]
Tried a drag and drop on redeploy in the redeploy-ships window under fleets and game log was here: 

06:24:14.523 [1] DEBUG General - AssignedShipListView.OnShipListSelectionChanged(): presentationModel.SelectedTaskForce.Name = 4 Starships

got this error log:

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=SupremacyClient
  StackTrace:
   at Supremacy.Client.Views.AssignedShipListView.OnShipListSelectionChanged(Object sender, SelectionChangedEventArgs e) in C:\Users\Kenneth Flanagan\Documents\97_BOTF2_20180906\BotF2\SupremacyClient\Views\GalaxyScreen\AssignedShipListView.xaml.cs:line 54
   at System.Windows.Controls.SelectionChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.ListBox.OnSelectionChanged(SelectionChangedEventArgs e)
   at System.Windows.Controls.Primitives.Selector.InvokeSelectionChanged(List`1 unselectedInfos, List`1 selectedInfos)
   at System.Windows.Controls.Primitives.Selector.SelectionChanger.End()
   at System.Windows.Controls.Primitives.Selector.OnItemsChanged(NotifyCollectionChangedEventArgs e)
   at System.Windows.Controls.ListView.OnItemsChanged(NotifyCollectionChangedEventArgs e)
   at System.Windows.Controls.ItemsControl.OnItemCollectionChanged2(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.Specialized.NotifyCollectionChangedEventHandler.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Windows.Data.CollectionView.OnCollectionChanged(NotifyCollectionChangedEventArgs args)
   at System.Windows.Controls.ItemCollection.SetCollectionView(CollectionView view)
   at System.Windows.Controls.ItemCollection.SetItemsSource(IEnumerable value, Func`2 GetSourceItem)
   at System.Windows.Controls.ItemsControl.OnItemsSourceChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.ScheduleTransfer(Boolean isASubPropertyChange)
   at MS.Internal.Data.ClrBindingWorker.NewValueAvailable(Boolean dependencySourcesChanged, Boolean initialValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.ClrBindingWorker.OnSourcePropertyChanged(Object o, String propName)
   at MS.Internal.Data.PropertyPathWorker.OnValueChanged(Object sender, ValueChangedEventArgs e)
   at System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   at MS.Internal.Data.ValueChangedEventManager.ValueChangedRecord.OnValueChanged(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at Supremacy.Client.Views.GalaxyScreenPresentationModel.OnSelectedTaskForceChanged() in C:\Users\Kenneth Flanagan\Documents\97_BOTF2_20180906\BotF2\SupremacyClientComponents\Views\GalaxyScreen\GalaxyScreenPresentationModel.cs:line 561
   at Supremacy.Client.Views.GalaxyScreenPresentationModel.set_SelectedTaskForce(FleetViewWrapper value) in C:\Users\Kenneth Flanagan\Documents\97_BOTF2_20180906\BotF2\SupremacyClientComponents\Views\GalaxyScreen\GalaxyScreenPresentationModel.cs:line 359
   at Supremacy.Client.Views.GalaxyScreenPresenter.OnTaskForcesChanged(Object sender, EventArgs e) in C:\Users\Kenneth Flanagan\Documents\97_BOTF2_20180906\BotF2\SupremacyClientComponents\Views\GalaxyScreen\GalaxyScreenPresenter.cs:line 724
   at Supremacy.Client.Views.GalaxyScreenPresentationModel.OnTaskForcesChanged() in C:\Users\Kenneth Flanagan\Documents\97_BOTF2_20180906\BotF2\SupremacyClientComponents\Views\GalaxyScreen\GalaxyScreenPresentationModel.cs:line 575
   at Supremacy.Client.Views.GalaxyScreenPresentationModel.set_TaskForces(IEnumerable`1 value) in C:\Users\Kenneth Flanagan\Documents\97_BOTF2_20180906\BotF2\SupremacyClientComponents\Views\GalaxyScreen\GalaxyScreenPresentationModel.cs:line 383
   at Supremacy.Client.Views.GalaxyScreenPresenter.RefreshTaskForceList() in C:\Users\Kenneth Flanagan\Documents\97_BOTF2_20180906\BotF2\SupremacyClientComponents\Views\GalaxyScreen\GalaxyScreenPresenter.cs:line 794
   at Supremacy.Client.Views.GalaxyScreenPresenter.ExecuteRemoveShipFromTaskForceCommand(RedeployShipCommandArgs args) in C:\Users\Kenneth Flanagan\Documents\97_BOTF2_20180906\BotF2\SupremacyClientComponents\Views\GalaxyScreen\GalaxyScreenPresenter.cs:line 271
   at Supremacy.Client.Input.DelegateCommand`1.Execute(T parameter) in C:\Users\Kenneth Flanagan\Documents\97_BOTF2_20180906\BotF2\SupremacyClientComponents\Input\DelegateCommand.cs:line 150
   at Supremacy.Client.Input.DelegateCommand`1.System.Windows.Input.ICommand.Execute(Object parameter) in C:\Users\Kenneth Flanagan\Documents\97_BOTF2_20180906\BotF2\SupremacyClientComponents\Input\DelegateCommand.cs:line 161
   at Microsoft.Practices.Composite.Presentation.Commands.CompositeCommand.Execute(Object parameter)
   at Supremacy.Client.Views.NewTaskForceDropTargetAdvisor.OnDropCompleted(IDataObject obj, Point dropPoint) in C:\Users\Kenneth Flanagan\Documents\97_BOTF2_20180906\BotF2\SupremacyClient\Views\GalaxyScreen\AvailableShipListView.xaml.cs:line 268
   at Supremacy.Client.DragDrop.DragDropManager.OnDropTargetPreviewDrop(Object sender, DragEventArgs e) in C:\Users\Kenneth Flanagan\Documents\97_BOTF2_20180906\BotF2\SupremacyClientComponents\DragDrop\DragDropManager.cs:line 171
   at System.Windows.DragEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.OleDropTarget.RaiseDragEvent(RoutedEvent dragEvent, Int32 dragDropKeyStates, Int32& effects, DependencyObject target, Point targetPoint)
   at System.Windows.OleDropTarget.MS.Win32.UnsafeNativeMethods.IOleDropTarget.OleDrop(Object data, Int32 dragDropKeyStates, Int64 point, Int32& effects)

**Comment by ExultantMonkey** [comment]
I'm guessing that #176 fixes this?

**Comment by KennethGF** [comment]
Think so. We will see.
