### ISSUE TITLE
Specified argument was out of the range of valid values at Supremacy.Utility.MersenneTwister.Next(Int32 maxValue)

### ISSUE THREAD

**Issue by ExultantMonkey** [BotF2/BotF2#162]
Played it for about 70 turns before I got this crash

```
Specified argument was out of the range of valid values.

   at Supremacy.Utility.MersenneTwister.Next(Int32 maxValue) in C:\Users\dwrj8\Repositories\BotF2\SupremacyCore\Utility\Random\MersenneTwister.cs:line 205
   at Supremacy.Utility.ChanceTree`1.Take() in C:\Users\dwrj8\Repositories\BotF2\SupremacyCore\Utility\Random\ChanceTree.cs.cs:line 103
   at Supremacy.Combat.InvasionEngine.ProcessBombardment() in C:\Users\dwrj8\Repositories\BotF2\SupremacyCore\Combat\InvasionArena.cs:line 915
   at Supremacy.Combat.InvasionEngine.ProcessRound() in C:\Users\dwrj8\Repositories\BotF2\SupremacyCore\Combat\InvasionArena.cs:line 789
   at Supremacy.Combat.InvasionEngine.SubmitOrders(InvasionOrders orders) in C:\Users\dwrj8\Repositories\BotF2\SupremacyCore\Combat\InvasionArena.cs:line 742
   at Supremacy.WCF.SupremacyService.<>c__DisplayClass86_0.<SendInvasionOrders>b__0() in C:\Users\dwrj8\Repositories\BotF2\SupremacyService\SupremacyService.cs:line 1449
   at Supremacy.Utility.GameScheduler.<>c__DisplayClass3_0.<Schedule>b__0() in C:\Users\dwrj8\Repositories\BotF2\SupremacyCore\Utility\GameScheduler.cs:line 45
   at System.Concurrency.ThreadPoolScheduler.<>c__DisplayClass1.<Schedule>b__0(Object _)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by bote-reginald** [comment]
"too old" - maybe not relevant anymore
