### ISSUE TITLE
Object reference not set to an instance of an object in AutomatedCombatEngine

### ISSUE THREAD

**Issue by ExultantMonkey** [BotF2/BotF2#164]
```
ERROR Combat Supremacy.WCF.SupremacyService.TryResumeCombat() - System.NullReferenceException: Object reference not set to an instance of an object.
   at Supremacy.Combat.AutomatedCombatEngine.ResolveCombatRoundCore() in C:\Users\dwrj8\Repositories\BotF2\SupremacyCore\Combat\AutomatedCombatEngine.cs:line 199
   at Supremacy.Combat.CombatEngine.ResolveCombatRound() in C:\Users\dwrj8\Repositories\BotF2\SupremacyCore\Combat\CombatEngine.cs:line 185
   at Supremacy.WCF.SupremacyService.TryResumeCombat(CombatEngine engine) in C:\Users\dwrj8\Repositories\BotF2\SupremacyService\SupremacyService.cs:line 1380
```

**Comment by KennethGF** [comment]
Is this still an issue?

**Comment by ExultantMonkey** [comment]
To be honest, I'm not really sure
