### ISSUE TITLE
Combat failing to end - resolve

### ISSUE THREAD

**Issue by KennethGF** [BotF2/BotF2#170]
Think there is some issue with the linq at line 90 in AutomatedCombatEngine.cs for the cloak strength camou strength branch

````07:05:10.280 [33] ERROR Combat Supremacy.WCF.SupremacyService.TryResumeCombat() - System.InvalidOperationException: Sequence contains no elements
at System.Linq.Enumerable.Max(IEnumerable`1 source)
at System.Linq.Enumerable.Max[TSource](IEnumerable`1 source, Func`2 selector)
at Supremacy.Combat.AutomatedCombatEngine.ResolveCombatRoundCore() in C:\Users\Kenneth Flanagan\Documents\94_BOTF2_20180922\BotF2\SupremacyCore\Combat\AutomatedCombatEngine.cs:line 90
at Supremacy.Combat.CombatEngine.ResolveCombatRound() in C:\Users\Kenneth Flanagan\Documents\94_BOTF2_20180922\BotF2\SupremacyCore\Combat\CombatEngine.cs:line 185
at Supremacy.WCF.SupremacyService.TryResumeCombat(CombatEngine engine) in C:\Users\Kenneth Flanagan\Documents\94_BOTF2_20180922\BotF2\SupremacyService\SupremacyService.cs:line 1380

**Comment by KennethGF** [comment]
Think adding a if (oppositionShips.Count() > 0) has resolved the issue. Will keep checking.

**Comment by ExultantMonkey** [comment]
How unusual. Surely oppositionShips should always > 0 otherwise there is no combat.......

**Comment by KennethGF** [comment]
Agree. Cannot explain it.
07:05:10.280 [33] ERROR Combat Supremacy.WCF.SupremacyService.TryResumeCombat() - System.InvalidOperationException: Sequence contains no elements

**Comment by ExultantMonkey** [comment]
This is exactly why I think that #169  is needed

**Comment by KennethGF** [comment]
appears to OK
