### ISSUE TITLE
Resolved? galaxy generator error due to too small maps?

### ISSUE THREAD

**Issue by KennethGF** [BotF2/BotF2#208]
````04:40:49.639 [7] ERROR General Supremacy.WCF.SupremacyService.DoStartGame() - An error occurred while starting a new game.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Supremacy.Universe.GalaxyGenerator.PlaceEmpireHomeworlds(CollectionBase`1 positions, IList`1 starNames, HomeSystemsDatabase homeSystemDatabase, List`1 empireCivs, CollectionBase`1 empireHomeLocations, List`1 chosenCivs, Boolean mustRespectQuadrants) in C:\Users\Kenneth Flanagan\Documents\92_BOTF2_20181117\BotF2\SupremacyCore\Universe\GalaxyGenerator.cs:line 602
   at Supremacy.Universe.GalaxyGenerator.PlaceHomeworlds(CollectionBase`1 positions, IList`1 starNames, CollectionBase`1& homeLocations) in C:\Users\Kenneth Flanagan\Documents\92_BOTF2_20181117\BotF2\SupremacyCore\Universe\GalaxyGenerator.cs:line 774

**Comment by KennethGF** [comment]
increased the size of the smallest map. Does not appear to generate odd maps with a lot of wormholes or radio pulsars. Will keep and eye out for other errors.

**Comment by KennethGF** [comment]
appears ok for now
