### ISSUE TITLE
Science ships doing research error

### ISSUE THREAD

**Issue by KennethGF** [BotF2/BotF2#277]
A siterep issue or research issue?
System.IndexOutOfRangeException
  HResult=0x80131508
  Message=Index was outside the bounds of the array.
  Source=mscorlib
  StackTrace:
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at Supremacy.Client.GameController.ProcessSitRepEntries() in C:\Users\kenne\Documents\96_BOTF2_20190126\BotF2\SupremacyClientComponents\IGameController.cs:line 354
   at Supremacy.Client.GameController.OnTurnStarted(EventArgs args) in C:\Users\kenne\Documents\96_BOTF2_20190126\BotF2\SupremacyClientComponents\IGameController.cs:line 346

**Comment by KennethGF** [comment]
not seeing this any more
