### ISSUE TITLE
A retreat error

### ISSUE THREAD

**Issue by KennethGF** [BotF2/BotF2#278]
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=SupremacyCore
  StackTrace:
   at Supremacy.Game.GameEngine.DoPreTurnOperations(GameContext game) in C:\Users\kenne\Documents\96_BOTF2_20190126\BotF2\SupremacyCore\Game\GameEngine.cs:line 376
   at Supremacy.Game.GameEngine.DoTurn(GameContext game) in C:\Users\kenne\Documents\96_BOTF2_20190126\BotF2\SupremacyCore\Game\GameEngine.cs:line 212
   at Supremacy.WCF.SupremacyService.<>c__DisplayClass48_0.<DoTurnCore>b__0() in C:\Users\kenne\Documents\96_BOTF2_20190126\BotF2\SupremacyService\SupremacyService.cs:line 591
   at System.Linq.Observable.<>c__DisplayClass130.<>c__DisplayClass132.<ToAsync>b__12f()

Inner Exception 1:
IndexOutOfRangeException: Index was outside the bounds of the array.

**Comment by KennethGF** [comment]
appears ok now, fix in place
