### ISSUE TITLE
Diplomacy crash on message selection, Could not load file or assembly 'Xaml, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

### ISSUE THREAD

**Issue by KennethGF** [BotF2/BotF2#280]
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'Xaml, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
  Source=System.Dataflow
  StackTrace:
   at System.Dataflow.Languages.MImageBase.LoadXaml(PackagePart part)
   at System.Dataflow.Languages.MImageBase.GetPartData(String partName, UriKind kind)
   at System.Dataflow.Languages.MImageBase.Load(Stream inputStream)
   at System.Dataflow.Languages.MImageBase.Initialize(Stream inputStream, Boolean closeOnDispose)
   at System.Dataflow.Languages.MImageBase..ctor(Stream inputStream, Boolean closeOnDispose)
   at Microsoft.M.MImage..ctor(Stream inputStream, Boolean closeOnDispose)
   at Supremacy.Scripting.Runtime.ScriptLanguageContext.EnsureParser() in C:\Users\ken\Documents\99_BOTF2_20190422\Supremacy.Scripting\Runtime\ScriptLanguageContext.cs:line 83
   at Supremacy.Scripting.Runtime.ScriptLanguageContext..ctor(ScriptDomainManager domainManager, IDictionary`2 options) in C:\Users\ken\Documents\99_BOTF2_20190422\Supremacy.Scripting\Runtime\ScriptLanguageContext.cs:line 250
   
This error is usually because you are referring to different versions of various HealthVault dlls.

Make sure ALL the dlls referred in the project (listed below) are from the same version of SDK

Microsoft.Health.dll
Microsoft.Health.Web.dll
Microsoft.ItemTypes.dll

Further at runtime, all HealthVault dlls in the bin folder should have exactly the same version.  The reference properties in Visual studio will show the version of the dll referred.

**Comment by KennethGF** [comment]
missing line in sln for loading xaml file.
