### ISSUE TITLE
Problem with collections

### ISSUE THREAD

**Issue by ExultantMonkey** [BotF2/BotF2#324]
In DoProduction, virtually every turn I'm getting an error message

Example
```
1:38:15.360 [48] ERROR Production Supremacy.Game.GameEngine+<>c__DisplayClass40_0.<DoProduction>b__0() - DoProduction failed for Vhnori
System.ArgumentOutOfRangeException: Index must be within the bounds of the List.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.Insert(Int32 index, T item)
   at Supremacy.Collections.IndexedCollection`1.InsertItem(Int32 listIndex, T item, Boolean upgradeableLockAlreadyHeld) in C:\Users\dwrj8\Repositories\BotF2\SupremacyCore\Collections\IndexedCollection.cs:line 359
   at Supremacy.Collections.IndexedCollection`1.Add(T item) in C:\Users\dwrj8\Repositories\BotF2\SupremacyCore\Collections\IndexedCollection.cs:line 340
   at Supremacy.Buildings.BuildingDesign.TrySpawn(MapLocation location, Civilization owner, TechObject& spawnedInstance) in C:\Users\dwrj8\Repositories\BotF2\SupremacyCore\Buildings\BuildingDesign.cs:line 260
   at Supremacy.Economy.BuildProject.Finish() in C:\Users\dwrj8\Repositories\BotF2\SupremacyCore\Economy\BuildProject.cs:line 424
   at Supremacy.Game.GameEngine.<>c__DisplayClass40_0.<DoProduction>b__0(Civilization civ) in C:\Users\dwrj8\Repositories\BotF2\SupremacyCore\Game\GameEngine.cs:line 1387
```

I believe this to be caused by some of the collections - the best I can figure for this one is thread issues.

There is no need for a lot of these custom collections nowadays. C# has added quite a lot, including concurrent ones.

I'm going to try and refactor them to use in built collections where possible. At least that way, Google might be able to help us narrow down the problem quicker in the future

**Comment by bote-reginald** [comment]
"too old" - maybe not relevant anymore
