### ISSUE TITLE
NullReferenceException in ShipyardUpgradeProject

### ISSUE THREAD

**Issue by ExultantMonkey** [BotF2/BotF2#325]
````21:38:05.907 [40] ERROR Production Supremacy.Game.GameEngine+<>c__DisplayClass40_0.<DoProduction>b__0() - DoProduction failed for Romulans
System.NullReferenceException: Object reference not set to an instance of an object.
   at Supremacy.Economy.ShipyardUpgradeProject.Finish() in C:\Users\dwrj8\Repositories\BotF2\SupremacyCore\Economy\StructureBuildProject.cs:line 192
   at Supremacy.Game.GameEngine.<>c__DisplayClass40_0.<DoProduction>b__0(Civilization civ) in C:\Users\dwrj8\Repositories\BotF2\SupremacyCore\Game\GameEngine.cs:line 1387

**Comment by bote-reginald** [comment]
"too old" - maybe not relevant anymore
