### ISSUE TITLE
Pla_g_ue vs Pla_q_ue

### ISSUE THREAD

**Issue by HappyGino** [BotF2/BotF2#455]
**Maybe there is an error on the name Pla_q_ue. Think it should be Pla_g_ue.  G instead of Q, depending on how it is written on the original file. Game did not crash but went into a pause, and it seems like it tried to find the right correspondance on the Web or I am completely out of it.**

System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Le fichier 'C:\Users\Gino\Documents\BOTF2_2019_cot_13_New\bin\Debug\Resources\Images\ScriptedEvents\Plaque.png' est introuvable.
  Source=mscorlib
  StackTrace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
   at Supremacy.VFS.HardDiskSource.InternalGetFile(String resolvedName, FileAccess access, FileShare share) in C:\Users\Gino\Documents\BOTF2_2019_cot_13_New\SupremacyCore\VFS\HardDiskSource.cs:line 283
   at Supremacy.VFS.HardDiskSource.HardDiskVirtualFileInfo.Open(FileAccess access, FileShare share) in C:\Users\Gino\Documents\BOTF2_2019_cot_13_New\SupremacyCore\VFS\HardDiskSource.cs:line 571
   at Supremacy.VFS.VirtualFileInfoExtensions.Open(IVirtualFileInfo self, FileAccess fileAccess) in C:\Users\Gino\Documents\BOTF2_2019_cot_13_New\SupremacyCore\VFS\VirtualFileInfoExtensions.cs:line 82
   at Supremacy.VFS.VirtualFileInfoExtensions.OpenRead(IVirtualFileInfo self) in C:\Users\Gino\Documents\BOTF2_2019_cot_13_New\SupremacyCore\VFS\VirtualFileInfoExtensions.cs:line 105
   at Supremacy.VFS.VfsWebResponse.GetResponseStream() in C:\Users\Gino\Documents\BOTF2_2019_cot_13_New\SupremacyCore\VFS\VfsWebRequest.cs:line 116
   at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   at System.Windows.Media.Imaging.BitmapFrame.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy)
   at System.Windows.Media.ImageSourceConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)

  This exception was originally thrown at this call stack:
	System.IO.__Error.WinIOError(int, string)
	System.IO.FileStream.Init(string, System.IO.FileMode, System.IO.FileAccess, int, bool, System.IO.FileShare, int, System.IO.FileOptions, Microsoft.Win32.Win32Native.SECURITY_ATTRIBUTES, string, bool, bool, bool)
	System.IO.FileStream.FileStream(string, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare)
	System.IO.File.Open(string, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare)
    Supremacy.VFS.HardDiskSource.InternalGetFile(string, System.IO.FileAccess, System.IO.FileShare) in HardDiskSource.cs
    Supremacy.VFS.HardDiskSource.HardDiskVirtualFileInfo.Open(System.IO.FileAccess, System.IO.FileShare) in HardDiskSource.cs
    Supremacy.VFS.VirtualFileInfoExtensions.Open(Supremacy.VFS.IVirtualFileInfo, System.IO.FileAccess) in VirtualFileInfoExtensions.cs
    Supremacy.VFS.VirtualFileInfoExtensions.OpenRead(Supremacy.VFS.IVirtualFileInfo) in VirtualFileInfoExtensions.cs
    Supremacy.VFS.VfsWebResponse.GetResponseStream() in VfsWebRequest.cs
	System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(System.Uri, System.IO.Stream, System.Windows.Media.Imaging.BitmapCacheOption, out System.Guid, out bool, out System.IO.Stream, out System.IO.UnmanagedMemoryStream, out Microsoft.Win32.SafeHandles.SafeFileHandle)
    ...
    [Call Stack Truncated]

**Comment by KennethGF** [comment]
This was fixed a while ago. Must have been overwritten at some point.
Created a new branch off master and put in a pull request for the code. The
image is still correct and creating the problem.
ken

**Comment by HappyGino** [comment]
Could have been overwritten in Dropbox while copying and pasting. Then if so, the same file would be fetched when the folder is required.
Sorry.

Gino


De : Kenneth Of Borg<mailto:notifications@github.com>
Envoyé le :18 décembre 2019 05:56
À : BotF2/BotF2<mailto:BotF2@noreply.github.com>
Cc : HappyGino<mailto:emilgo47@hotmail.com>; Author<mailto:author@noreply.github.com>
Objet :Re: [BotF2/BotF2] Error in System IO FileNotFoundException (#455)

This was fixed a while ago. Must have been overwritten at some point.
Created a new branch off master and put in a pull request for the code. The
image is still correct and creating the problem.
ken

**Comment by KennethGF** [comment]
Does not look like you did anything wrong.
ken

**Comment by HappyGino** [comment]
I did not move or copy any file as of yet, but if you mention that everything is ok and no one did it, then it must be in Visual Studio itself that the file is wrong since we often push and pull with the same version. Maybe we must search in the files in there I guess, to find where and which one it is.

Gino

**Comment by HappyGino** [comment]
Ok. Finally found the file and corrected it **I guess it is The Good One** Did a search in Visual Studio, It was PlaqueSitRepEntry. Renamed it PlagueSitRepEntry and did commit in my version. 
We will have to add to all versions when we meet.

**Comment by KennethGF** [comment]
We try to keep version control from over writting old fixes. Now and then
one gets through. Congrats on finding it. Was an easy fix. Waiting on merge
so go ahead and approve, merge and delete branch.

ken

**Comment by HappyGino** [comment]
Thank you Ken,
Will approve and merge but waiting for our meeting sunday to delete the branch.

Gino

Bonne journée! Have a nice day!

De : Kenneth Of Borg<mailto:notifications@github.com>
Envoyé le :19 décembre 2019 10:08
À : BotF2/BotF2<mailto:BotF2@noreply.github.com>
Cc : HappyGino<mailto:emilgo47@hotmail.com>; Author<mailto:author@noreply.github.com>
Objet :Re: [BotF2/BotF2] Error in System IO FileNotFoundException (#455)

We try to keep version control from over writting old fixes. Now and then
one gets through. Congrats on finding it. Was an easy fix. Waiting on merge
so go ahead and approve, merge and delete branch.

ken

**Comment by HappyGino** [comment]
OK, merged and deleted the GitHub branch for Plague.
Still not sure how to make changes in my local version, pulling and change branches so will wait for you.

Bonne journée! Have a nice day!

De : Kenneth Of Borg<mailto:notifications@github.com>
Envoyé le :19 décembre 2019 10:08
À : BotF2/BotF2<mailto:BotF2@noreply.github.com>
Cc : HappyGino<mailto:emilgo47@hotmail.com>; Author<mailto:author@noreply.github.com>
Objet :Re: [BotF2/BotF2] Error in System IO FileNotFoundException (#455)

We try to keep version control from over writting old fixes. Now and then
one gets through. Congrats on finding it. Was an easy fix. Waiting on merge
so go ahead and approve, merge and delete branch.

ken
