### ISSUE TITLE
Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by ExultantMonkey** [BotF2/BotF2#6]
Randomly came up

```
Exception has been thrown by the target of an invocation.

at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) 
at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) 
at System.Delegate.DynamicInvokeImpl(Object[] args) 
at System.Delegate.DynamicInvoke(Object[] args) 
at Supremacy.Utility.AsyncHelper.AsyncInvokeCallback(Object state) in SupremacyCore\Utility\AsyncHelper.cs:line 54 
at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() 
at System.Threading.ThreadPoolWorkQueue.Dispatch() 
at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

Collection was modified; enumeration operation may not execute.

at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource) 
at System.Collections.Generic.List1.Enumerator.MoveNextRare() 
at System.Collections.Generic.List1.Enumerator.MoveNext() 
at System.Linq.Enumerable.CountTSource 
at Supremacy.Combat.CombatEngine.get_IsCombatOver() in SupremacyCore\Combat\CombatEngine.cs:line 88
at Supremacy.WCF.SupremacyService.SendCombatUpdateCallback(CombatEngine engine, CombatUpdate update) in SupremacyService\SupremacyService.cs:line 1137
```

**Comment by KennethGF** [comment]
Part of this could have been address by adding assets.ToList() in the foreach loop counting assests.
