### ISSUE TITLE
Crash with only Federation and Terran as playable

### ISSUE THREAD

**Issue by ExultantMonkey** [BotF2/BotF2#7]
```
System.ArgumentException occurred
  HResult=0x80070057
  Message=Collection already contains an item with the specified key.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Supremacy.Collections.KeyedCollectionBase`2.OnKeyCollision(TKey key, TValue item) in C:\Users\dwrj8\Repositories\supremacydev\Mainline\SupremacyCore\Collections\ObservableKeyedCollection.cs:line 330
   at Supremacy.Collections.KeyedCollectionBase`2.AddKey(TKey key, TValue item) in C:\Users\dwrj8\Repositories\supremacydev\Mainline\SupremacyCore\Collections\ObservableKeyedCollection.cs:line 310
   at Supremacy.Collections.KeyedCollectionBase`2.InsertItem(Int32 index, TValue item) in C:\Users\dwrj8\Repositories\supremacydev\Mainline\SupremacyCore\Collections\ObservableKeyedCollection.cs:line 243
   at Supremacy.Collections.CollectionBase`1.Add(T item) in C:\Users\dwrj8\Repositories\supremacydev\Mainline\SupremacyCore\Collections\CollectionBase.cs:line 116
   at Supremacy.Universe.GalaxyGenerator.FinalizaHomeworldPlacement(IList`1 starNames, HomeSystemsDatabase homeSystemDatabase, Civilization civ, MapLocation location) in C:\Users\dwrj8\Repositories\supremacydev\Mainline\SupremacyCore\Universe\GalaxyGenerator.cs:line 353
   at Supremacy.Universe.GalaxyGenerator.PlaceEmpireHomeworlds(CollectionBase`1 positions, IList`1 starNames, HomeSystemsDatabase homeSystemDatabase, List`1 empireCivs, CollectionBase`1 empireHomeLocations, List`1 chosenCivs, Boolean mustRespectQuadrants) in C:\Users\dwrj8\Repositories\supremacydev\Mainline\SupremacyCore\Universe\GalaxyGenerator.cs:line 522
   at Supremacy.Universe.GalaxyGenerator.PlaceHomeworlds(CollectionBase`1 positions, IList`1 starNames, CollectionBase`1& homeLocations) in C:\Users\dwrj8\Repositories\supremacydev\Mainline\SupremacyCore\Universe\GalaxyGenerator.cs:line 721
   at Supremacy.Universe.GalaxyGenerator.GenerateGalaxy(GameContext game) in C:\Users\dwrj8\Repositories\supremacydev\Mainline\SupremacyCore\Universe\GalaxyGenerator.cs:line 219
   at Supremacy.Game.GameContext.Initialize() in C:\Users\dwrj8\Repositories\supremacydev\Mainline\SupremacyCore\Game\GameContext.cs:line 936
   at Supremacy.Game.GameContext..ctor(GameOptions options, Boolean isMultiplayerGame) in C:\Users\dwrj8\Repositories\supremacydev\Mainline\SupremacyCore\Game\GameContext.cs:line 872
   at Supremacy.Game.GameContext.Create(GameOptions options, Boolean isMultiplayerGame) in C:\Users\dwrj8\Repositories\supremacydev\Mainline\SupremacyCore\Game\GameContext.cs:line 858
   at Supremacy.WCF.SupremacyService.DoStartGame() in C:\Users\dwrj8\Repositories\supremacydev\Mainline\SupremacyService\SupremacyService.cs:line 255
```

```
01:20:37.501 [6] DEBUG General - GalaxyGenerator.PlaceEmpireHomeworlds(): Civilization Intro placed as Empire
01:20:37.506 [6] DEBUG General - GalaxyGenerator.PlaceEmpireHomeworlds(): Civilization Federation placed as Empire
01:20:37.514 [6] WARN  General - Failed to find a suitable home sector for civilization Terran Empire.  Galaxy generation will start over.
01:20:37.989 [6] DEBUG General - GalaxyGenerator.PlaceEmpireHomeworlds(): Civilization Intro placed as Empire
01:20:37.994 [6] DEBUG General - KeyedCollectionBase`2.OnKeyCollision(): ####### KeyCollision: key=0; item=Supremacy.Game.CivilizationManager
```

**Comment by bote-reginald** [comment]
works now
