### ISSUE TITLE
ShowDialog problems

### ISSUE THREAD

**Issue by ExultantMonkey** [BotF2/BotF2#88]
DEBUG General - Dialog.ShowDialog(): Cannot call ShowDialog() on a dialog that was already opened with ShowDialog().
DEBUG General - Dialog.ShowDialog(): Cannot call ShowDialog() on a dialog that is already open.

**Comment by ExultantMonkey** [comment]
System.InvalidOperationException
  HResult=0x80131509
  Message=View already exists in region.
  Source=Microsoft.Practices.Composite.Presentation
  StackTrace:
   at Microsoft.Practices.Composite.Presentation.Regions.Region.InnerAdd(Object view, String viewName, IRegionManager scopedRegionManager)
   at Microsoft.Practices.Composite.Presentation.Regions.Region.Add(Object view, String viewName, Boolean createRegionManagerScope)
   at Supremacy.Client.Dialogs.Dialog.ShowInternal() in C:\Users\dwrj8\Repositories\BotF2\SupremacyClientComponents\Dialogs\Dialog.cs:line 589
   at Supremacy.Client.Dialogs.Dialog.ShowDialog() in C:\Users\dwrj8\Repositories\BotF2\SupremacyClientComponents\Dialogs\Dialog.cs:line 556

**Comment by bote-reginald** [comment]
did not notice that problem recently
